DUMMY_ADDR = "_"
READ_OPERATION = "Read"
WRITE_OPERATION = "Write"
ACCESSED_MARK = "Accessed"
DUMMY = (DUMMY_ADDR, 0)

# ORAM choice constants
SIMULATION_MEGA_BLOCKS_ORAM = '1'
MEGA_BLOCKS_ORAM = '2'
PATH_ORAM = '3'
COUNTER_PATH_ORAM = '4'
COUNTER_MEGA_BLOCKS_ORAM = '5'
COUNTER_FUTORAMA = '6'